project:
  type: website
  output-dir: docs

website:
  title: "The LSE Roundtable on DSI"
  navbar:
    left:
      - href: index.qmd
        text: Background
      - href: presentations.qmd
        text: Presentations
      - href: interim_ways_forward.qmd
        text: Interim Ways Forward



format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

