project:
  type: website
  output-dir: docs

website:
  twitter-card: true
  image: "https://github.com/oneworldanalytics/biodiversity-finance-dsi/blob/master/pointing_to_cali.jpeg"
  #pointing_to_cali.jpeg
  #"https://github.com/oneworldanalytics/biodiversity-finance-dsi/blob/master/baobab_tree.jpg"
  body-footer: |
        <!-- 100% privacy-first analytics -->
        <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
        <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  title: "The LSE Roundtable on DSI"
  navbar:
    left:
      - href: index.qmd
        text: Background
      - href: presentations.qmd
        text: Presentations
      - href: interim_ways_forward.qmd
        text: Ways Forward



format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

