project:
  type: website
  output-dir: docs

website:
  title: "The LSE Roundtable on DSI"
  navbar:
    left:
      - href: index.qmd
        text: Background
      - href: presentations.qmd
        text: Day One
      - href: presentations2.qmd
        text: Day Two



format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

