---
title: "Ways Forward"
---

The LSE Roundtable brought together experts from a range of fields, industry and database representatives and negotiators from the major UN regions to consider three main questions:

a\) What criteria can be used to determine the size of the fund?

b\) Who should contribute and based on what measures?

c\) How can trust be promoted in the DSI data ecosystem?

The views in this Ways Forward document reflect the analysis of LSE team members based on the discussions at the Roundtable. Full materials from the Roundtable are available [here](https://oneworldanalytics.com/biodiversity-finance-dsi/presentations.html).

### **The Size of the Fund**

DSI is a digital economic asset of global importance. A range of methods are available for valuing data, but to date, no work has been initiated to establish the value of DSI based on the quality and informational content of the asset. The transition to natural capital accounting provides an opportunity to assess the value of DSI data within the United Nations System of National Accounts (the SNA) and wider UN economic reporting framework. Parties may wish to initiate further work on approaches to valuing DSI within the context of natural capital accounting and the UN system for economic reporting (see also Decision 15/5, para 4).

In the absence of work on DSI valuation, a decision on the size of the fund is essentially political. Parties may wish to create a means for measuring future success by establishing an interim target as a *floor* for the fund that can be scaled up based on operational experience and an improved process for DSI valuation. To explore this, a ‘[toy model](https://www.dropbox.com/scl/fi/571c4fm7s0a4lm8yil9bo/Kamath_TOY_MODEL_To_be_printed.xlsx?rlkey=4ppi09aipdx0xq4caeokn5ejv&st=yh4yd2im&dl=0)’ for a fund of US\$2-20 billion per year was created to assess contributions divided by country and weighted by annual GDP. Parties are invited to consider supporting further work on economic modelling to assess scenarios for the fund including different thresholds for contributions.

### **Who Should Pay?**

A [model](https://www.dropbox.com/scl/fi/12pytjixbvmawio869dwf/Makowska-Revenue-Model-Components-Table-PRINTED.pptx?rlkey=b8hxgviuu29gojol7bfgxzzlq&st=t0haqk1u&dl=0) of Options A to D identified sources of information available to governments or to the public and considered the as yet undefined concept of ‘DSI reliance’.^[\[1\]](#_ftn1)^  Given the data sources presently available, attempts to define ‘DSI reliant’ products with legal certainty are likely to fail.

The United Nations Statistics Division (UNSD) is the steward of a family of classifications agreed by member states as part of the framework of economic reporting and the System of National Accounts. The International Standard Industrial Classification of All Economic Activities (ISIC) classifies entities by type of economic activity and forms the basis for regional and national classifications in use worldwide by governments for the organisation of economic reporting by industry and sectors. ISIC is directly linked to a number of classification systems for products, services and intellectual property through the Central Product Classification (CPC) and the World Customs Organization’s Harmonized System (HS) for international trade in goods. Patent and statistical authorities also use classification schemes to map trends in activity by sector. These classifications are linked to industries and cover thousands of product groups. The classifications are routinely used in economic reporting by governments. Product classifications can assist in identifying sectors that *directly* or *indirectly* benefit from DSI.

Parties are invited to use the family of economic classification systems operated by the United Nations Statistics Division including, *inter alia*; the International Standard Industrial Classification of All Economic Activities (ISIC), the Central Product Classification (CPC) and Harmonised System (HS) and their regional and national equivalents to support implementation of the multilateral mechanism on DSI. Inputs from the UNSD and regional and national statistical authorities, including patent authorities, on the use of the classification family for the implementation of the international mechanism on DSI would be helpful.

[Pay Nature First: Profit vs Sales/Turnover]{.underline}

The Roundtable concluded that sales/turnover is the appropriate measure based on the principles of ‘paying nature first’ and treating contributions to the DSI fund as a pre-profit cost of doing business.

In accountancy the terms sales, revenue and turnover are different words for the same thing.^[\[2\]](#_ftn2)^ The real distinction is between profit and sales/turnover. Using profit can protect new and small businesses who may have high sales but low profits, but profits are more likely to be manipulated, and fluctuations in profit could cause yearly variations in the funds raised.  Further, full data is only available to tax authorities. In contrast, data on sales/turnover is less open to manipulation and is more widely available on the sector level and for exports as part of the System of National Accounts and UN reporting framework.

Taking into account the different characteristics of economies and economic activity a *basket of measures* led by sales/turnover but including profit and the value of total assets as the formula for the calculation of contributions is the most likely to be equitable. Such a basket can be led by a percentage of sales/turnover and include different bands across which the percentage varies. To give flexibility in defining fair thresholds for contributions from entities of different sizes (i.e. different bands), a ‘2 out of 3’ approach is recommended for meeting the thresholds out of sales/turnover, profit/net income and value of total assets. Using averages over 3 years for the above metrics can remove the effect of spikes and troughs in activity.

Experience in the EU strongly suggests that ‘opt out’ approaches to contributions combined with disclosures (e.g. CSR/ESG) will work best. In ‘opt out’ systems all entities meeting certain criteria are assumed to be in the bucket. Entities may be able to opt out where a justification is made against a set of criteria, transferring the burden of proof to entities (e.g. [EU REACH legislation](https://environment.ec.europa.eu/topics/chemicals/reach-regulation_en)). Experience in the EU, India & China with Corporate Social Responsibility (CSR)/Environment, Social and Governance (ESG) reporting reveals positive impacts on company behaviour and may make companies more attractive to investors. Combining opt out with disclosure approaches would avoid a need for Parties to legally define DSI. 

Contributions from entities should be based on guiding principles such as the FRETAP principles: that they be Fair (apply to all), Reasonable (e.g. not 99% of sales), Equitable (across economies), Transparent (public) and Predictable.^[\[3\]](#_ftn3)^

### **Creating Trust by Doing: Conditions for Trust in the DSI Data Ecosystem**

Decision 15/9 includes references to the 2021 UNESCO Recommendation on Open Science, the OECD Recommendation on Enhancing Access to and Sharing of Data, the FAIR and CARE principles and encourages the deposit of DSI in public databases. In order to operationalise these goals and ensure a return for biodiversity from the use of global public DSI data a new architecture of trust is needed in the DSI ecosystem. That trust can only be achieved through practical action.

The ability to maintain relationships between samples and digital objects such as sequences is central to modern science. Recognition that modern science involving DSI depends on identifiers opens up opportunities to support good scientific practice *and* improve transparency to Parties using standard scientific templates such as those used for BioSamples (sample metadata). At the same time Parties, through guidance from funding agencies, could promote greater awareness of the importance of accurate metadata within the scientific community. Building on increasing requirements for location information from INSDC, these small but important steps could radically improve the transparency of DSI to Parties and Indigenous Peoples and local communities.

Using identifiers for accessions allows nucleotide sequences to be mapped to protein sequences and, in turn, allows proteins to be mapped to tools such as EMBL-EBI and Google’s Alphafold2. EMBL-EBI and Google Alphafold2 data is made available under a permissive Creative Commons Attribution Licence (CC-BY). However, recent efforts by Google to obtain a return on its investment in AI in AlphaFold3 raises the question of how public databases as custodians of global public DSI data should act with respect to such commercial opportunities. To generate conditions of trust and secure a return for biodiversity, Parties may wish to consider the use of a Sovereign Commons Licence (SCL). ^[\[4\]](#_ftn4)^

United Nations member states enjoy permanent sovereignty over their natural resources. The proposed Sovereign Commons Licence pools authorisation for the sharing and use of digital sequence information linked with obligations for benefit sharing through the multilateral benefit sharing mechanism; while retaining sovereignty.  Parties would require that sequences with the SCL would only be submitted to databases and repositories participating in the multilateral mechanism. Parties would set out the impact, terms of use and conditions of benefit sharing in the SCL. Parties to the Nagoya Protocol, at their discretion, could use the SCL as the default licence in MAT. It would be open to other UN member states to use the SCL in the sharing of sequence data. Parties would take steps to recognise and respect the rights of Indigenous Peoples set out in UNDRIP in the SCL. Such a licence could be iteratively updated based on operational experience.

[\[1\]](#_ftnref1) See Agata Makowska-Curran [Mapping DSI Options A-D](https://www.dropbox.com/scl/fi/1hrvbshoatptfi0widc5x/Makowska-Curran_DSI-Models.pptx?rlkey=8lrn2iu035d43sssr4sh0bqwi&st=q681dqfl&dl=0)

[\[2\]](#_ftnref2) Saipriya Kamath [Unlocking Private Capital: Navigating Regulation, Metrics and Investor Motivation](https://www.dropbox.com/scl/fi/m0radq2vc9apc2k1lscz7/Kamath_unlocking_private_capital.pptx?rlkey=i5kt0aji1k4etsl9v9es4vmqo&st=ew4m55xr&dl=0)

[\[3\]](#_ftnref3) Paul Oldham and Siva Thambisetty 2024 The Pandemic Access and Benefit Sharing System: Four Elements of a Trusted System. https://dx.doi.org/10.2139/ssrn.4877517

[\[4\]](#_ftnref4) Paul Oldham and Siva Thambisetty 2024 [The Sovereign Commons Licence](https://www.dropbox.com/scl/fi/bv46r6269o59lvj9nx2el/The-Sovereign-Commons-Licence.pdf?rlkey=rvmhwslxxn39iwwm8ijvzhu3l&st=2m7fwh4i&dl=0).
