---
title: "Presentations from Day Two"
---

### Data Valuation, Trust and the Sovereign Commons License

##### Paul Oldham

Paul Oldham from One World Analytics pointed to the inclusion of the OECD Recommendation on Enhancing Access to and Sharing of Data and the UNESCO Recommendation on Open Science in Decision 15/9 and argued that the nature of these documents is sometimes misunderstood. He used the example of the privatisation of Alphafold 3, originally based on openly available data from EMBL-EBI, to raise questions on ensuring returns for biodiversity. He pointed to the importance of maintaining relationships between different kinds of data to maintain transparency in how it is being used and put forward the suggestion of a Sovereign Commons Licence, whereby Parties, in the collective exercise of their sovereign rights could decide to establish a common licence for the sharing of digital sequence information.

A further elaboration on the concept of the Sovereign Commons License from Paul Oldham and Siva Thambisetty is available [here](https://www.dropbox.com/scl/fi/t8wu0ibo9gty5t0gpsyyi/The-Sovereign-Commons-Licence.pdf?rlkey=yng82qofess1w9vfghgmch6xv&st=rqbnmvrq&dl=0){target="_blank"}.

###### [Slides](https://www.dropbox.com/scl/fi/779sga69h9k8oo5fao892/oldham_data_trust_alphafold.pptx?rlkey=6eb8rfajg2hxvr3c58xeh4ejm&st=053tmw19&dl=0){target="_blank"}

### MGR and DSI on MGR in the BBNJ Treaty

##### Siva Thambisetty

Siva Thambisetty from the LSE reflected on the implications and lessons learned from the BBNJ Treaty for DSI in the context of the CBD. She highlighted the obligations related to Party reporting under the legally binding Treaty, emphasizing the requirement to report the origin of genetic material from which the DSI is sourced, using a Batch Identifier. Additionally, she discussed the obligation for databases holding data within the scope of the BBNJ to report aggregate-level data every two years. She concluded that the direction of travel is towards the use of identifiers and the mapping of aggregate data flows, and that this shift is necessary to foster trust and emphasized that databases should play a key role in the architecture of trust.

###### [Slides](https://www.dropbox.com/scl/fi/omteyjqkqa15nznes1jzh/Thambisetty-BBNJ-for-LSE-Roundtable.pptx?rlkey=34jifm9umf4g7xb7bu56yzymo&st=8q534f8s&dl=0)

### The Perspective from the Plant Treaty

##### Alvaro Toledo

Alvaro Toledo from the Plant Treaty Secretariat discussed the subscription model under the Plant Treaty, their use of SMTAs, the importance of data collection to understand the industry landscape and their use of a tiered system for contributions under their multilateral system.

(No links available)

### GBIF's Approach to Open Access to Data within a Framework of Trust and Transparency

##### Tim Hirsch 

Tim Hirsch provided an overview of GBIF as an organization, illustrating how its data is used globally. He explained GBIF's use of Creative Commons licenses for their data and highlighted their user agreement, which clarifies that while GBIF data is free of cost to users, it is not free of responsibilities. He also discussed GBIF's practice of assigning DOIs to datasets, which enhances transparency in data usage and enables tracking the impact of GBIF data in research and policymaking, while ensuring proper recognition for data providers.

###### [Slides](https://www.dropbox.com/scl/fi/g489i1m661iseo8pc2npv/Hirsch-GBIF-240928_LSE_DSI.pptx?rlkey=pklvb114lgnwnx5smhgjh1p86&st=qntwf3en&dl=0){target="_blank"}

### The INSDC: 40 Years of Trust

##### Masanori Arita

Masanori Arita from the DDBJ addressed common questions regarding the INSDC collaboration, including their use of metadata and their efforts to integrate the FAIR and CARE (without the A) principles. He also expressed concerns about DDBJ’s capacity to work with commercial cloud services and the feasibility of the INSDC registering users or charging for access to the database.


###### [Slides](https://www.dropbox.com/scl/fi/ncegsu6pmzxsejj0vr9bl/Masanori_insdc_LSE.pptx?rlkey=x7s2wfu0pviscvrnjt3taurd2&st=0qh3xl3k&dl=0){target="_blank"}

### The Global Biodata Infrastructure

##### Chuck Cook

Chuck Cook from the Global Biodata Coalition emphasized that sequence data gains value through comparison with other sequences and as it moves through the biodata resource infrastructure. This infrastructure is an interdependent network of databases and repositories holding various types of biodiversity data, extending beyond genetic sequences to include structures, compounds, interactions, and pathways. He also highlighted the insufficiency of funding to support the current infrastructure and stressed the importance of the free flow of information for the advancement of global science.

###### [Slides](https://www.dropbox.com/scl/fi/fgcmknk5i4tadi23ev3v8/Cook_Global_Biodata_LSE_roundtable.pdf?rlkey=m7rbehdgm7u8ort50ghidj10p&st=ry7riq5j&dl=0)



